### ISSUE TITLE
Range Picker Feature

### ISSUE THREAD

**Issue by mario-aleo** [fooloomanzoo/datetime-picker#10]
Hello,

First, congratulations for the great work on this component, it's amazing.
It would be even awesome if you could put a range picker feature, by day, month or year, on this component :D

Thanks,
Mario Aleo

**Comment by fooloomanzoo** [comment]
I'm not exactly shure, what you mean. In the examples there is a way on how to connect to elements with there `min` and `max` attributes where you can realize a range of dates:

 ```javascript
                <datetime-picker use-not-native value="{{min}}" max="{{max}}" vertical-align="bottom"></datetime-picker>
                <datetime-picker use-not-native value="{{max}}" min="{{min}}" vertical-align="top"></datetime-picker>
```

![image](https://user-images.githubusercontent.com/9318952/30329078-86343cd4-97d1-11e7-9aa4-45e8694c4564.png)

Or do you mean in one picker?

**Comment by fooloomanzoo** [comment]
@mario-aleo There is now a new release, that handles `min` and `max` correctly. There have been some mistakes how to check if the actual value is valid. These problems are now solved and a range picker can realized like it is described in the examples. An extra element for that is not really necessary, but may come in future
