### ISSUE TITLE
Doesn't work with Polymer 1

### ISSUE THREAD

**Issue by romanesko** [fooloomanzoo/datetime-picker#16]
requires /polymer/polymer-element.html 
(which is missing in polymer 1)

**Comment by fooloomanzoo** [comment]
+ What version are you using of polymer 1? `>1.9.2`?
+ Aren't elements `polymer 1` also work in `polymer 2`? Why don't you upgrade?

**Comment by fooloomanzoo** [comment]
After doing a research, I am still not really sure how to realize a complete `1.x` version but I found this:
- [https://github.com/Polymer/polymer/issues/4103#issuecomment-331312682](https://github.com/Polymer/polymer/issues/4103#issuecomment-331312682)
- [http://jsbin.com/qavacax/edit?html,output](http://jsbin.com/qavacax/edit?html,output)

In Polymer `2.x` you should be able to use both, but in Polymer `1.x` you might need to implement the element like in the second example. But I would recommend to you that you upgrade your project to `2.x`.
