### ISSUE TITLE
Different date-formats selection.

### ISSUE THREAD

**Issue by Devni94** [fooloomanzoo/datetime-picker#19]
Is it possible to display date (in date-input element) in different formats? 
ex: ( DD/MM/YYYY or MM/DD/YYYY or YYYY/DD/MM or YYYY/MM/DD) 
 
Following is the code snippet from date-input.html
I tried meddling with this to no avail.
```
<number-input style="order:[[_orderDate.month]];" index$="[[_orderDate.month]]" hidden$="[[_hideMonth]]" pad-length="2" min="1" max="12" disabled="[[disabled]]" value="{{month}}"></number-input>
<span style="order:[[_orderDate.separatorYearMonth]];" hidden$="[[_hideMonth]]">[[_localDateSeparator]]</span>
<number-input style="order:[[_orderDate.year]];" index$="[[_orderDate.year]]" pad-length="4" disabled="[[disabled]]" value="{{year}}"></number-input>
<span style="order:[[_orderDate.separatorMonthDay]];" hidden$="[[_hideDay]]">[[_localDateSeparator]]</span>
<number-input style="order:[[_orderDate.day]];" index$="[[_orderDate.day]]" hidden$="[[_hideDay]]" pad-length="2" min="1" max="[[_maxDayOfMonth]]" disabled="[[disabled]]" value="{{day}}"></number-input>
${super.inputTemplate || ''}
```
Any hints/knowlege/suggestions are highly appreciated.

**Comment by fooloomanzoo** [comment]
You can set a different locale to the attribute `locale`, for example `en` for the English DateTimeFormat (MM/DD/YYYY), `fr` for the French DateTimeFormat (DD/MM/YYYY) or `jp` for the Japanese DateTimeFormat (YYYY/MM/DD). All Formats your Browser can provide this element will test for. By default the locale of you Browser is used, but you can set it manually. You can find an example on bottom of the [demo](https://fooloomanzoo.github.io/datetime-picker/components/datetime-picker/)

**Comment by Devni94** [comment]
First of all let me apologize for not observing properly. 
Yes, this is the kind of feature I was looking for. 
I inspected this `DatetimeMixin._localeChanged()` before I opened this issue, But I could not get the hang of it. 
Thank you very much!

**Comment by Devni94** [comment]
Is there any way I can change the format in the date-input element but not the calendar?

**Comment by fooloomanzoo** [comment]
`<date-input>` is linked with the `<date-picker>` inside the template by the `locale` and other attributes.
You could create a new element and extend the element you like, and overwrite the `replacementInputTemplate` to assign different data-bindings. For example, this would be what you expect:

```html
    <link rel="import" href="../polymer/polymer-element.html">
    <link rel="import" href="../datetime-picker/date-picker.html">

    <dom-module id="picker-date">
      <script>
        /**
         *  @customElement
         *  @polymer
         *
         *  @extends DatePicker
         **/
        class PickerDate extends DatePicker {

          static get is() {
            return 'picker-date';
          }

          static get properties() {
            return {
              localeForInput: {
                type: String
              }
            }
          }

          static get replacementInputTemplate() {
            return `
              <date-input class="replacement" locale="[[localeForInput]]" hour12=[[hour12]] clamp="[[clamp]]" datetime="{{confirmedDatetime}}" min="[[min]]" max="[[max]]"></date-input>
            `;
          }
        }
        window.customElements.define(PickerDate.is, PickerDate);
      </script>
    </dom-module>
```

`locale` and `localeForInput` are so separated.

**Comment by Devni94** [comment]
Thanks a bunch @fooloomanzoo . Really appreciate your help with this.
