### ISSUE TITLE
RangeMixin is not defined

### ISSUE THREAD

**Issue by ralexrdz** [fooloomanzoo/datetime-picker#23]
`RangeMixin is not defined`

When using any of the components I get this error. Any idea why? files are there

I'm using webpack

**Comment by fooloomanzoo** [comment]
Do you find `/bower_components/property-mixins/range-mixin.html` in your file structure? If yes, then does it also happen, if you don't use webpack?

**Comment by fooloomanzoo** [comment]
@ralexrdz It might have been an issue with my `range-mixin.html`. If you try `bower update -f` again, does the problem still occur?

**Comment by fooloomanzoo** [comment]
@ralexrdz Does it work for your webpack-setting? How do you configure webpack by the way so that it works with polymer?

**Comment by ralexrdz** [comment]
Trying to understand and get ahead of Polymer 3 way of deploying, which sounded quite nice beacause of the power of Webpack
[Getting Started with Polymer 3 0](https://www.youtube.com/watch?v=aU6y16StdGA)

And following partly this
[Polymer + Webpack: Bringing Web Components to a Framework Near You (Polymer Summit 2017)](https://www.youtube.com/watch?v=LpMI_Do5t5U)

Thanks a lot for the attenttion
