### ISSUE TITLE
Layout looks weird on Safari

### ISSUE THREAD

**Issue by johanbyren** [fooloomanzoo/datetime-picker#27]
The layout seems to go all over the place on Safari. All other browsers it is great. 
![image](https://user-images.githubusercontent.com/7137075/34149341-0ccfe94e-e4a5-11e7-9e3b-e92e76674211.png)

![image](https://user-images.githubusercontent.com/7137075/34149408-40a72c6e-e4a5-11e7-9c92-f76d7527f7f4.png)

Link: https://codepen.io/johanbyren/pen/RxaawW (It works fine in chrome but looks weird in Safari)

**Comment by fooloomanzoo** [comment]
Sorry, I can not test the element on Safari. But there were changes for the layout since the version you are using. Does it still look weird on Safari when you update your elements?

**Comment by johanbyren** [comment]
Yes sorry, It's no different.

**Comment by fooloomanzoo** [comment]
it looks like the input replacement takes more than it should. There could be a difference on how Safari treats "inline-flex".

**Comment by fooloomanzoo** [comment]
I had the change to see the problem on Safari and its a one-liner. It is fixed in the newest version
