### ISSUE TITLE
Empty value

### ISSUE THREAD

**Issue by brettpostin** [fooloomanzoo/datetime-picker#33]
Apologies if I've missed something, but I can't see a way to set an empty value? 

In the absence of data I would like a blank field rather than it default to the current date/time.

Is there a way to achieve this?

**Comment by fooloomanzoo** [comment]
By default the today is the picked date, if not any attribute is set, but I might change that behaviour

**Comment by brettpostin** [comment]
Ok thanks for the clarification.

I would love to use this element as it looks the most complete datetime picker available. However at present I cannot see how I would use this in a form where the field value may not be required.

I noticed there is a required property, what function does this serve if the field always has a value?

**Comment by fooloomanzoo** [comment]
The `required` property comes from my `FormElementMixin` and this mixin is used also by other input elements I made. For Polymer's `iron-form`-element it is required for an element to have a validate function and so I created this mixin and included some shared attributes. Formerly it did not have that attribute, but I look into it.

**Comment by brettpostin** [comment]
Support for empty values would be a welcome addition.

**Comment by fooloomanzoo** [comment]
@brettpostin It should be possible with the new update.

**Comment by brettpostin** [comment]
Awesome thank you! Is there a way to clear the value back to empty once it has been set?

**Comment by fooloomanzoo** [comment]
Right and thanks, should be fixed in the current version
