### ISSUE TITLE
Week title does not match the dates

### ISSUE THREAD

**Issue by adrysn** [fooloomanzoo/datetime-picker#36]
Hi. I found that the week title does not match the date.

You'll exactly know what I mean after looking at the image. I tried to attach a calendar image from my site, but the same phenomenon appears on the [official demo site](https://www.webcomponents.org/element/fooloomanzoo/datetime-picker), so I will upload it.

<img width="447" alt="2018-02-23 1 20 37" src="https://user-images.githubusercontent.com/7539358/36550104-c738a152-1837-11e8-86c4-18c9c5580cc1.png">

Feb 23 2018 should be Friday, but the calendar indicates it is Thursday.

When I replace `- 1` to `- 2` in [this line](https://github.com/fooloomanzoo/datetime-picker/blob/master/calendar-element.html#L331), it is okay. But, it does not seem to be the correct fix.

I am not sure this is happening only in my location (Korea+09:00). I saw an image of other issues and it was fine!

---
OS: macOS High Sierra 10.13.3
Browser: Chrome (64.0.3282.167)
datetime-picker version: 2.7.4 (Polymer 2.5.0)

**Comment by fooloomanzoo** [comment]
Thanks and you were right an did have something to do with the local timezone. In the newest version it should be fixed.
