### ISSUE TITLE
I wrote a blog featuring your component

### ISSUE THREAD

**Issue by binhbbui411** [fooloomanzoo/datetime-picker#39]
Here's the link to the blog: https://vaadin.com/blog/web-component-wednesday-1-datepicker  
  
I think you have a great component and decided that it would be a cool one to be included on the blog. Feel free to write some comments on the blog.

**Comment by fooloomanzoo** [comment]
@binhbbui411 Thank you, I am just wondering why you did choose the calendar element althought there are the date-picker and the the datetime-picker that match better the theme and title of your blog-post?

**Comment by binhbbui411** [comment]
Hey @fooloomanzoo, thanks for reading the blog. I was actually writing this piece several months ago when this was still an issue https://github.com/fooloomanzoo/datetime-picker/issues/14.  So I just recycled the material I have written and go with it.  
  
Another reason is that I want to promote the usability of a sub-element of a web-component. My blog targets newbies, and usually, they are quite clueless about this whole thing in general. By using a sub-element, I'm stating how big and versatile a web-component can be that you don't always need to use the main element.

**Comment by binhbbui411** [comment]
Anyhow, you have an amazing component. Kudos to that!
