### ISSUE TITLE
Input fields for time-element do not display value with Firefox

### ISSUE THREAD

**Issue by lpellegr** [fooloomanzoo/datetime-picker#4]
It works on Chrome but not Firefox.

![screenshot from 2017-06-27 11-29-53](https://user-images.githubusercontent.com/128898/27580762-f8a354b8-5b2b-11e7-996c-57aa588c634b.png)

I do not see any specific error message in the console.

**Comment by fooloomanzoo** [comment]
Which Firefox-Version are using? Are you using the new polymer-2.0-version? On my computer it looks like (Firefox 54.0):
![image](https://user-images.githubusercontent.com/9318952/27586901-8fd97248-5b42-11e7-8682-a085dcc6c343.png)
, so I can't reproduce the issue.

**Comment by lpellegr** [comment]
@fooloomanzoo Finally, I had the time to investigate a bit. The issue appears when I customize `datetime-picker-input` as follows:

```
datetime-picker {
    --datetime-picker-input: {
        background-color: #e1e8fd;
        border-radius: 4px;
        border: 0;
        font-size: 14px;
        height: 20px;
        line-height: 20px;
        margin-left: 8px;
        padding: 16px;
        width: 110px;
    }
}
```

The style is not rendered the same way on Chrome and Firefox when `padding: 16px` is used.

A workaround is to override your `box-sizing` definition on `#time`:

```
box-sizing: content-box;
```

Then, the rendering looks consistent.
