### ISSUE TITLE
Errors in Safari

### ISSUE THREAD

**Issue by aryakrishnan** [fooloomanzoo/datetime-picker#40]
I have tried the picker component, but it is not working with Safari Version 10.1.1.

Errors in console,

TypeError: Attempted to assign to readonly property.
TypeError: undefined is not an object (evaluating 'observerHandle.disconnect')

Can you please help me to resolve this problem?

**Comment by fooloomanzoo** [comment]
I currentlly don't have a Mac so I am not able to debug for Safari. Does it say in which component this is happening?

**Comment by aryakrishnan** [comment]
I was using overlay-datetime-picker component.

Please find the error log screenshot.

<img width="687" alt="test" src="https://user-images.githubusercontent.com/10267602/37353015-778d8448-2704-11e8-99f7-9df15988e991.png">
![Uploading test1.png…]()

**Comment by fooloomanzoo** [comment]
Ok, it doesn't say anything. When I am nexttime using a Mac I try to debug it.

**Comment by mercmobily** [comment]
I am following this issue too. I am about to use your fantastic element, but.. I really really need it to work on Safari. Incidentally, I don't have a Mac either. How can we make this happen?

**Comment by fooloomanzoo** [comment]
@mercmobily It could have been now with the latest updates. Could you please recheck?

**Comment by mercmobily** [comment]
Shall I ask a friend with a Mac to have a look? Would you be able to have it online somewhere?

**Comment by fooloomanzoo** [comment]
You could ask if [this codepen](https://codepen.io/fooloomanzoo/pen/RxqNOb) and the [webcomponents demos](https://www.webcomponents.org/element/fooloomanzoo/datetime-picker/demo/demo/datetime-elements.html) are working, when clicking on the pickers

**Comment by aryakrishnan** [comment]
@fooloomanzoo @mercmobily Now the demo is working fine for me. No issues so far.
