### ISSUE TITLE
Unable to modify time in DateTime picker using local dependencies

### ISSUE THREAD

**Issue by Fleker** [fooloomanzoo/datetime-picker#41]
I've been running into a really weird issue trying to use this widget where I can change the date, but the time never updates in the field (but it does in the calendar popup) using the `datetime-picker` element.

![image](https://user-images.githubusercontent.com/3291635/37375292-22bb676e-26dc-11e8-9662-27939bbad891.png)

![image](https://user-images.githubusercontent.com/3291635/37375318-380966d4-26dc-11e8-823f-314798a5e2d2.png)

Pressing the confirm button doesn't update the field.

I was able to run it fine using one of your example snippets, which made it even more bizarre.

```HTML
<base href="https://raw-dot-custom-elements.appspot.com/fooloomanzoo/datetime-picker/2.7.11/datetime-picker/"
<script src="../webcomponentsjs/webcomponents-lite.js"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="import" href="datetime-picker.html">
```

Using these imports are fine, but when I swap those out to the (I assume) identical files downloaded via Bower, the issue is present.

```HTML
<script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="import" href="bower_components/datetime-picker/datetime-picker.html">
```

The files do exist, and I don't see any errors in the console about setting up. Can you think of any reason that I may be having this issue?

Via Bower, I have installed v1.1.0 of `webcomponentsjs` and v2.7.11 of `datetime-picker`. Am I missing something?

**Comment by Jaytn** [comment]
I seem to have the same issue.

I prodded around and saw that the hosted version has some older dependencies than the one downloaded by bower.
After much manual file switching (I don't really know my way around bower), I found which dependencies exactly make it work:
- Swapping in `property-mixins-2.3.2/datetime-mixin.html` (only this file, swapping the whole folder breaks it) will make the time-pickers in the overlay work again - but the element still shows 00:00:00
- Swapping in `datetime-input-2.2.3` will make the element show the correct time

I hope this will help you figure out the issue.

In the meantime maybe this is helpful as a workaround for someone. 🙂

**Comment by fooloomanzoo** [comment]
There were some changes in updating the datetime-subproperties. In the newest version `2.8.2` everything should be fixed. Consider the style-property changes (`--input-picker-color` and `--input-picker-background` define now the apperance of the picker). Please update by `bower update -f`
