### ISSUE TITLE
NumberInput^2.7.10 breaks non-native datetime input. 

### ISSUE THREAD

**Issue by aarondrabeck** [fooloomanzoo/datetime-picker#42]
![image](https://user-images.githubusercontent.com/9825025/37382769-30a3e27e-270a-11e8-8b36-cba53c4fcb58.png)

**Comment by MrMcGibblets** [comment]
We also have this issue, not been able to pinpoint the exact change. We have changed our bower.json to the previous version's and is working there.  If you need it working before a fix is made you can change yours to below:

 "datetime-picker": "fooloomanzoo/datetime-picker#2.7.10",
 "number-input": "fooloomanzoo/number-input#2.1.9",
 "datetime-input": "fooloomanzoo/datetime-input#2.2.3",
 "property-mixins": "fooloomanzoo/property-mixins#2.3.2",
 "input-picker-pattern": "fooloomanzoo/input-picker-pattern#2.1.7"

**Comment by fooloomanzoo** [comment]
There were some changes in sizing the number-input. In the newest version `2.8.2` everything should be fixed. Consider the style-property changes (`--input-picker-color` and `--input-picker-background` define now the apperance of the picker). Please update by `bower update -f`
