### ISSUE TITLE
Datetime picker doesn't work and displays CSS (2.8.5)

### ISSUE THREAD

**Issue by Fleker** [fooloomanzoo/datetime-picker#45]
After #41 I updated to 2.8.2 and ~2.8.2 (which resolves to 2.8.5). In both cases, I am seeing some really odd behavior. With my same setup (copying the demo code and replacing with my local code) I am still unable to get it to render like in your demos. The picker doesn't show a calendar anymore, only the time with some weird line breaks (also, the time picker does work but doesn't show in the input). Plus I'm seeing a lot of CSS just on the page.

![image](https://user-images.githubusercontent.com/3291635/38059574-c9077e76-329b-11e8-9ca2-6d3a651e8865.png)

![image](https://user-images.githubusercontent.com/3291635/38059620-fb3f1584-329b-11e8-8fcf-3b4b6f4bdbde.png)

```HTML
<script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="import" href="bower_components/datetime-picker/datetime-picker.html">
```

**Comment by fooloomanzoo** [comment]
It should be fixed with the new version `2.8.7`. Please consider the new way of [styling](https://github.com/fooloomanzoo/datetime-picker#styling).
