### ISSUE TITLE
Styling is not good in Edge

### ISSUE THREAD

**Issue by fat-crienturu** [fooloomanzoo/datetime-picker#46]
In Edge the datetime-picker doesn't look very good.

![image](https://user-images.githubusercontent.com/25978973/38263133-8b02abb8-376f-11e8-90ce-866890d1fa39.png)
- the width of the inputs is too small so it cuts off the last number.
- colors of the date and time separators is white so it's not visible.
- when a date or time is selected, then everything turns white so nothing is visible any more.

When you define your own colors, then there are also issues in the calendar/time popup:
- font color for the month, year and time inputs turns white even if they were defined as black
This is Edge (month, year and time are not visible in the popup):
![image](https://user-images.githubusercontent.com/25978973/38263688-09ceef0a-3771-11e8-9782-3f861131bd5c.png)

This is Chrome (everything is visible):
![image](https://user-images.githubusercontent.com/25978973/38263389-4bb44858-3770-11e8-9fe1-4f24f730fb81.png)

Here is a codepen which demonstrates the issues:
https://codepen.io/anon/pen/MVBjxr

**Comment by fooloomanzoo** [comment]
It should be fixed with the new version `2.8.7`. Please consider the new way of [styling](https://github.com/fooloomanzoo/datetime-picker#styling).

**Comment by fooloomanzoo** [comment]
Are you shure that you really updated every dependency with `bower update -f`? For the webcomponents page it could also be necessary to clear the browser cache. Everything works for me in IE 11.

**Comment by fat-crienturu** [comment]
Thank you for looking into it.
I didn't update any dependencies. In the codepen I'm using the ones you're serving: https://raw-dot-custom-elements.appspot.com/fooloomanzoo/datetime-picker/2.8.7/datetime-picker

I tried clearing the cache for Edge, but it didn't help. It also work in IE11 for me.

I'm assuming you don't have Windows 10 to try it out in Edge. Do you know that Microsoft has free virtual machines with Edge for testing: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ Could you maybe try it in that?

**Comment by fooloomanzoo** [comment]
Thanks for the link. I will try it out

**Comment by fooloomanzoo** [comment]
@fat-crienturu In the newest version it should be fixed. In edge inputs are sized differently and it has problems with currentColor.

**Comment by fooloomanzoo** [comment]
@fat-crienturu you could try it in this [codepen ](https://codepen.io/anon/pen/VXNxrZ)

**Comment by fat-crienturu** [comment]
@fooloomanzoo thank you for the fixes, that looks much better.

I noticed there is still one issue left, the time part in the popup is still white so it's not visible on a white background.

**Comment by fooloomanzoo** [comment]
@fat-crienturu yes I just saw that too. Is fixed in `2.8.9`
