### ISSUE TITLE
Non-native pickers on-tap arrows are no longer working

### ISSUE THREAD

**Issue by lpellegr** [fooloomanzoo/datetime-picker#5]
Non-native pickers are no longer working with version _2.0.3_.

Steps to reproduce:

1. Open https://fooloomanzoo.github.io/datetime-picker/components/datetime-picker/demo/.
2. Tap on month selector for non-native (picker appears).
3. Try to change the current month: next or after arrows are not working. 

The same applies for the time picker when I try to increase or decrease hours using the arrows.

I used Chrome _60_ and Firefox _54_.

**Comment by lpellegr** [comment]
Ouawww, after looking at the implementation I understood that you have to hold for a few milliseconds for having the arrows that behave correctly. It's really not intuitive. Clicking on the arrow should trigger the action button.

**Comment by fooloomanzoo** [comment]
You are right, at least the first should click should change the value immeadiatly. I implemented this trigger to emulate a long press event on touch devices. Working on it

**Comment by fooloomanzoo** [comment]
changed: https://github.com/fooloomanzoo/datetime-picker/releases/tag/2.0.5
