### ISSUE TITLE
Quitting editing, or resetting field to null

### ISSUE THREAD

**Issue by mercmobily** [fooloomanzoo/datetime-picker#55]
Once a user has clicked on a field, there seem to be no way to get "out" of editing.
Is there a way to cancel the date picking? Escape doesn't seem to do the trick.

Help? :D

**Comment by fooloomanzoo** [comment]
In the release `2.9.2` are a lot of changes made. If you click outside, press `esc` or click the `x`-button the picker should be canceled and closed.
