### ISSUE TITLE
Feature request: fire event on value reset

### ISSUE THREAD

**Issue by witoldlitwin** [fooloomanzoo/datetime-picker#56]
Hi! Could you add another event which would be fired when a user clicks on the small x reset button next to current field value? It would be useful for some validation scenarios we're working on.

**Comment by fooloomanzoo** [comment]
If an user clicks the reset button, the value will be `undefined`. If the input has an `required`-attribute, the property `invalid` will be set. Have you first try to work with those kind of changes?

**Comment by witoldlitwin** [comment]
Observer for the `invalid` property did the trick. Thanks!
