### ISSUE TITLE
Clamp values incorrect in the documentation

### ISSUE THREAD

**Issue by witoldlitwin** [fooloomanzoo/datetime-picker#57]
I noticed a mismatch between the docs and the code. The docs state:

> Clamp datetime to a property possible values:'month', 'day', 'hour', 'minute', 'second', 'millisecond'

while it should be 'minute**s**', 'second**s**', 'millisecond**s**'

**Comment by fooloomanzoo** [comment]
No, in the code it is different. Have a [look at](https://github.com/fooloomanzoo/property-mixins/blob/master/datetime-mixin.html#L751)
