### ISSUE TITLE
calendar-element When confirm, it autoSubmit  form

### ISSUE THREAD

**Issue by tandacedric** [fooloomanzoo/datetime-picker#58]
I have the date-picker in my  form(iron-form). When i choose  and confirm date on date-picker with calendar, it auto submit my form.

**Comment by fooloomanzoo** [comment]
What do you mean by ìt submits my form`?

**Comment by fooloomanzoo** [comment]
The only thing the element does, that it implements a validation function so that iron-form can validate the input value. Submitting is part part of your implementation. Please have a look at the demo for the element in an iron-form in the demo-folder. Don't forget the name attribute.

**Comment by tandacedric** [comment]
this is my code,  i am use  **datetime-picker 2.9.1**
`
<link rel="import" href="../../bower_components/polymer/polymer-element.html">

<dom-module id="page-setting-school-years">
  <template>
    <style is="custom-style" include="shared-styles iron-flex iron-flex-reverse iron-flex-alignment iron-flex-factors iron-positioning">
      :host {
        display: block;
      }
    </style>

    <div class="layout vertical">

      <iron-form id="form1" on-iron-form-submit="doSumit">
        <form action="/foo" method="get">
          name:
          <input name="name" value="Batman" />
          <br> job:
          <input name="job" value="Hero" />
          <br>
          <br> first day:
          <date-picker name="first" max="{{end}}" confirmed-value="{{start}}"></date-picker>
          <br> last day:
          <date-picker name="last" min="{{start}}" confirmed-value="{{end}}"></date-picker>
          <br>
          <br> last job:
          <datetime-picker name="lastjob" min="[[start]]" max="[[end]]" date="{{lastjob}}" property-for-value="datetime"></datetime-picker>
          <br> return:
          <time-picker name="return" min="[[lastjob]]" max="[[end]]" confirmed-value="{{return}}"></time-picker>
          <br>
          <br>
          <button on-click="form1submit">Submit</button>
          <button onclick="form1.validate()">Validate</button>
        </form>
        <div id="output"></div>
      </iron-form>

    </div>
  </template>

  <script>
    class PageSettingSchoolYears extends Polymer.Element {
      static get is() { return 'page-setting-school-years'; }
      static get properties() {
        return {}

      }
      doSumit(event) {
        this.$.output.innerHTML = JSON.stringify(event.detail);
      }
      form1submit(event) {
        this.$.form1.submit();
      }

      constructor() {
        super();
      }
      ready() {
        super.ready();
      }
      connectedCallback() {
        super.connectedCallback();

      }
      disconnectedCallback() {
        super.disconnectedCallback();
      }
      attributeChangedCallback() {
        super.attributeChangedCallback();
      }
    }
    window.customElements.define(PageSettingSchoolYears.is, PageSettingSchoolYears);
  </script>
</dom-module>`
