### ISSUE TITLE
Typing values manually

### ISSUE THREAD

**Issue by madiganz** [fooloomanzoo/datetime-picker#63]
Currently the element allows a user to keep typing numbers into the date or time fields. This causes the date to get completely messed up. For example, let's say a date is 10/30/2018. If a user adds a 1 to the day, it will add 301 days and display what that date + 301 days is. I would expect the element to not accept input after maximum values are reached.

**Comment by fooloomanzoo** [comment]
Reason for this kind of behavior was, to enable to shift to next or prevois month for example. In the new behavior when you type a too large value for day for example, the new date will be at the next month's first day.

**Comment by madiganz** [comment]
So you are saying that it goes to the next month's first day. For example my example would take you to 11/01/2018? I do not see this happening.

**Comment by fooloomanzoo** [comment]
On which site are you testing? On your local test-setup or on github/webcomponents? Those demos-sites I will update soon, but if you install it, it should work or I can not reproduce your issue

**Comment by madiganz** [comment]
I was able to reproduce it on both. What version was this updated in? I am currently running v2.9.1 locally, which is most likely the reason.
